services:
  - type: web
    name: flask-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python BACKEND.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
